# Generated by Django 4.1.3 on 2022-11-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
