# Generated by Django 4.1.3 on 2022-11-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='defautTitle', max_length=100)),
                ('image', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
