# Generated by Django 4.1.3 on 2022-11-26 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='image',
            new_name='image_url',
        ),
    ]
