# Generated by Django 4.1.3 on 2022-11-26 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0002_rename_image_problem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='userOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
