# Generated by Django 4.1.3 on 2022-11-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0005_alter_problem_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="userOf",
        ),
    ]
