# Generated by Django 4.1.3 on 2022-11-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0007_problem_userof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="status",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
